{
    "0": "Horror \"Tsurube-Otoshi Apparition\"",
    "2": "Trap Sign \"Capture Web\"",
    "4": "Spider \"Cave Spider's Nest\"",
    "6": "Miasma Sign \"Filled Miasma\"",
    "8": "Miasma \"Unexplained Fever\"",
    "10": "Jealousy Sign \"Green-Eyed Monster\"",
    "12": "Envy \"Green-Eyed Invisible Monster\"",
    "14": "Illuson Bomb \"Mind Starmine\"",
    "16": "Illusion Bomb \"Starmine Glare\"",
    "18": "Illusion Sign \"Double-sight \"",
    "20": "Shortsight \"X-Wave\"",
    "22": "Illusion Sign \"Water Bullet\"",
    "24": "Water Illusion \"Water Bullets\"",
    "26": "Phantasm Sign \"Spirit,Ghoul And Will o Wisp\"",
    "30": "Chirplaigrism \"Hell's Wheel of Pain\"",
    "32": "Chirplaigrism \"Shackles a Criminal Can't Take Off\"",
    "34": "Chirplaigrism \"Storm on Mt. Ooe\"",
    "36": "Chirplaigrism \"Wind Blowing Down from Mt. Ooe\"",
    "38": "Chirplaigrism \"Knock Out In Three Steps\"",
    "40": "Chirplaigrism \"Knock Out In Three Steps\"",
    "42": "Recollection \"Terrible Souvenir\"",
    "44": "Recollection \"Terrifying Hypnotism\"",
    "46": "Intense Winds \"Suwako Moriya's Whirlwind\"",
    "50": "Suwa War \"Wisteria Vines\"",
    "54": "Suwako \"A Pond Native to A Million Frogs\"",
    "58": "Recollection \"Mt. Togakushi Toss\"",
    "62": "Recollection \"Night Parade of a Million Demons\"",
    "66": "Recollection \"Deep Fog Labyrinth\"",
    "70": "Recollection \"Wind God's Tornado\"",
    "74": "Recollection \"Wind Miracle\"",
    "78": "Recollection \"Kanako's Circle\"",
    "82": "Backstab \"Thousand Daggers for Kaguya\"",
    "86": "Fujiwara no Mokou \"Immortality's Reckless Sacrifice -Blue-\"",
    "90": "Thousand Flames \"Bamboo Forest on Fire\"",
    "94": "Recollection \"Mercury Poison\"",
    "98": "Recollection \"Princess Undine\"",
    "102": "Recollection \"Philosopher's Stone\"",
    "106": "Chirplaigrism \"I Tried to Turn it Into a Two Winged Heron\"",
    "110": "Flame \"Mokous's Pororoca\"",
    "114": "Creeping Flames \"Flame of 60 Years\"",
    "118": "Cat Sign \"Cat's Blade\"",
    "120": "Cat Sign \"500 Blade Step\"",
    "122": "Blade Sign \"Blade of the Sun\"",
    "124": "Blade Sign \"A Blade made out of the Sun\"",
    "126": "Shattered Blade \"Shards of Higekirimaru\"",
    "128": "Bewitched Sword \"Not a Silver Blade\"",
    "130": "Atonement \"50000 Blades in One Flash\"",
    "132": "Atonement \"Sugiroshis Blade Barrage\"",
    "134": "\"A Celestial's Secret Technique\"",
    "136": "Sugiroshi\"Thousandth Blade of Kusanagi\"",
    "138": "Sakuya Izayoi \"Eternal Meek?\"",
    "142": "Divine Winds \"Solar Winds\"",
    "144": "Divine Winds (Atomic Fire) \"Solar Winds of The Yataragatsu\"",
    "145": "Divine Winds (Blazing Flames)\"Uncontainable Solar Winds\"",
    "146": "Headwind \"Route Forbidden To Man\"",
    "147": "Headwind \"Route Forbidden to Youkai\"",
    "148": "Headwind \"Route Forbidden to Tsukumogamis\"",
    "149": "Explosive Headwind \"Solar Storm (Rock)\"",
    "150": "Blazing Star \"Fixed Star\"",
    "152": "Blazing Star \"Planetary Revolution\"",
    "153": "Blazing Star \"Ten Evil Stars\"",
    "154": "\"Hell & Heaven Meltdown\"",
    "156": "\"Hell's Tokamak\"",
    "158": "\"Hell's Artificial Sun\"",
    "160": "\"Subterranean Sun\"",
    "162": "Esoterica \"Nine Syllable Stabs\"",
    "163": "Miracle \"Miracle Fruit\"",
    "164": "Divine Virtue \"Bumper Crop Rice Shower\"",
    "165": "5000 Degree Flames \"Subterannean Sun (Fossil Fuel\"",
    "166": "A Truly Impossible Request \"Field of A Thousand Jeweled Hourai Trees\"",
    "167": "Tenryū  \"Divine Virtues of Wind God\"",
    "168": "Suppression \"Super-Ego\"",
    "169": "Response \"Youkai Polygraph\"",
    "170": "Unconscious \"Rorschach in Danmaku\"",
    "171": "Rekindled \"The Embers of Love\"",
    "172": "Depths \"Genetics of the Unconscious\"",
    "173": "\"Philosophy of a Hated Person\"",
    "174": "\"Subterranean Rose\""
}